// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUECVc0X9xp4reSIN0VRApVtmoBwTERU4',
    appId: '1:754576855855:web:4694a4afb56f27d7c007da',
    messagingSenderId: '754576855855',
    projectId: 'presence-app-55ec9',
    authDomain: 'presence-app-55ec9.firebaseapp.com',
    storageBucket: 'presence-app-55ec9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgfihgkMU_QVrFdN-EsZbN1xxcuypk2ac',
    appId: '1:754576855855:android:e31aa63f0de69d60c007da',
    messagingSenderId: '754576855855',
    projectId: 'presence-app-55ec9',
    storageBucket: 'presence-app-55ec9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF1KKZis4BGGWIYFOKKvwvFYpVVj7D-u8',
    appId: '1:754576855855:ios:1809498905d7a8ccc007da',
    messagingSenderId: '754576855855',
    projectId: 'presence-app-55ec9',
    storageBucket: 'presence-app-55ec9.firebasestorage.app',
    iosClientId: '754576855855-bklknbmlqhtqdiel9i6o06iqdfdmjlfc.apps.googleusercontent.com',
    iosBundleId: 'com.fahmi.presence',
  );
}
